  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/ssafy?serverTimezone=Asia/Seoul
      username: root
      password: ssafy
      driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true

    server:
      port: 80
      servlet:
        contextPath: /justmoveit